apiVersion: v1
data:
  mapRoles: "- groups:\n- system:masters\nrolearn: arn:aws:iam::815482982786:role/UdacityFlaskDeployCBKubectlRole\nusername:
    build    \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::815482982786:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-13EZ3NSYHIUD0\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-12T12:31:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "21042"
  uid: 1a994e25-cc2f-4c07-9467-4f1f2459b368
