apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::140822796883:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CY6KJ19GHPGG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::140822796883:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-13T06:33:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1284"
  uid: 0ad926f3-7a0d-47cd-b8b9-8978e60e06d9